/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Readiness: 200 when the database answers, 503 otherwise.
         *
         *     Args:
         *         response: Used to set the status code.
         *
         *     Returns:
         *         The health report.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description Liveness: the process serves HTTP (used by the Docker healthcheck).
         *
         *     Returns:
         *         A constant ``ok``.
         */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Me
         * @description Return the identity behind the access token.
         *
         *     Args:
         *         user: The authenticated caller.
         *
         *     Returns:
         *         The caller's subject, scopes and permissions.
         */
        get: operations["read_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Trips
         * @description List the caller's trips.
         *
         *     Args:
         *         user: The authenticated organizer.
         *         session: Database session.
         *
         *     Returns:
         *         Trips, newest first.
         */
        get: operations["list_trips_trips_get"];
        put?: never;
        /**
         * Create Trip
         * @description Create a trip owned by the caller.
         *
         *     Args:
         *         data: Trip payload.
         *         user: The authenticated organizer.
         *         session: Database session.
         *
         *     Returns:
         *         The created trip.
         */
        post: operations["create_trip_trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{trip_id}/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Profiles
         * @description List the people on one of the caller's trips.
         *
         *     Args:
         *         trip_id: Trip id.
         *         user: The authenticated organizer.
         *         session: Database session.
         *
         *     Returns:
         *         The trip's profiles.
         */
        get: operations["list_profiles_trips__trip_id__profiles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planning/fairness/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Score
         * @description Score one candidate plan.
         *
         *     Args:
         *         request: Utilities and weights of every person.
         *
         *     Returns:
         *         The weighted log welfare.
         */
        post: operations["score_planning_fairness_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planning/linter/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check
         * @description Lint a plan.
         *
         *     Args:
         *         request: Plan and budget.
         *
         *     Returns:
         *         All violations.
         */
        post: operations["check_planning_linter_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{trip_id}/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Expenses
         * @description List expenses of one of the caller's trips.
         *
         *     Args:
         *         trip_id: Trip id.
         *         user: The authenticated organizer.
         *         session: Database session.
         *
         *     Returns:
         *         The trip's expenses.
         */
        get: operations["list_expenses_trips__trip_id__expenses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expenses/settlement/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Balances
         * @description Compute net balances for a set of payments.
         *
         *     Args:
         *         request: Payments to settle.
         *
         *     Returns:
         *         Balance per person.
         */
        post: operations["balances_expenses_settlement_balances_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgeGroup
         * @description Age group that drives default constraints (distance, naps, pace).
         * @enum {string}
         */
        AgeGroup: "child" | "teen" | "adult" | "senior";
        /**
         * BalancesRequest
         * @description Payments to settle.
         */
        BalancesRequest: {
            /** Payments */
            payments: components["schemas"]["Payment"][];
        };
        /**
         * BalancesResponse
         * @description Net balance per person: positive means they are owed money.
         */
        BalancesResponse: {
            /** Balances */
            balances: {
                [key: string]: string;
            };
        };
        /**
         * ExpenseRead
         * @description An expense as returned by the API.
         */
        ExpenseRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /**
             * Payer Profile Id
             * Format: uuid
             */
            payer_profile_id: string;
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
            /** Description */
            description: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FairnessRequest
         * @description Utilities of every person for a single candidate plan.
         */
        FairnessRequest: {
            /** People */
            people: components["schemas"]["PersonUtility"][];
        };
        /**
         * FairnessScore
         * @description Objective value of a plan: sum of w_i * log(1 + u_i).
         */
        FairnessScore: {
            /** Score */
            score: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Overall status plus the database check.
         */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "unavailable";
            /** Environment */
            environment: string;
        };
        /**
         * LintReport
         * @description All violations found in a plan.
         */
        LintReport: {
            /** Violations */
            violations: components["schemas"]["Violation"][];
        };
        /**
         * LintRequest
         * @description A plan to check plus the group budget.
         */
        LintRequest: {
            /** Items */
            items: components["schemas"]["PlanItem"][];
            /** Budget */
            budget: number | string;
        };
        /**
         * LiveResponse
         * @description Process liveness.
         */
        LiveResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /**
         * MeResponse
         * @description Response of ``GET /me``.
         */
        MeResponse: {
            /** Sub */
            sub: string;
            /** Scopes */
            scopes: string[];
            /** Permissions */
            permissions: string[];
        };
        /**
         * Payment
         * @description Who paid how much, and who shares the cost (split equally).
         */
        Payment: {
            /** Payer */
            payer: string;
            /** Amount */
            amount: number | string;
            /** Participants */
            participants: string[];
        };
        /**
         * PersonUtility
         * @description One person's satisfaction with a plan and their vote weight.
         */
        PersonUtility: {
            /**
             * Utility
             * @description Satisfaction u_i, 0-100.
             */
            utility: number;
            /**
             * Weight
             * @description Vote multiplier w_i.
             * @default 1
             */
            weight: number;
        };
        /**
         * PlanItem
         * @description One stop in a plan.
         */
        PlanItem: {
            /** Name */
            name: string;
            /**
             * Cost
             * @default 0
             */
            cost: number | string;
        };
        /**
         * ProfileRead
         * @description A person on a trip.
         */
        ProfileRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /** Display Name */
            display_name: string;
            age_group: components["schemas"]["AgeGroup"];
            /**
             * Weight
             * @description Vote multiplier in the fairness solver.
             */
            weight: number;
        };
        /**
         * TripCreate
         * @description Payload for creating a trip.
         */
        TripCreate: {
            /** Name */
            name: string;
            /** Destination */
            destination?: string | null;
        };
        /**
         * TripRead
         * @description A trip as returned by the API.
         */
        TripRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Destination */
            destination: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Violation
         * @description A single broken rule.
         */
        Violation: {
            /** Rule */
            rule: string;
            /** Message */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
        };
    };
    read_me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_trips_trips_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripRead"][];
                };
            };
        };
    };
    create_trip_trips_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_profiles_trips__trip_id__profiles_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_planning_fairness_score_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FairnessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FairnessScore"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_planning_linter_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LintRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LintReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_expenses_trips__trip_id__expenses_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpenseRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    balances_expenses_settlement_balances_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BalancesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalancesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
