#!/usr/bin/env node
// Architecture rules dependency-cruiser cannot express (it sees imports, not files or syntax).
// Run through `pnpm test:arch`.
import { readdirSync, readFileSync } from 'node:fs'
import { join, relative } from 'node:path'

const SRC = 'src'
const failures = []

function walk(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name)
    return entry.isDirectory() ? walk(path) : [path]
  })
}

const files = walk(SRC).map((path) => relative('.', path))

// Paraglide's output is generated, so the per-file rules below skip it.
const handWritten = files.filter((file) => !file.startsWith('src/paraglide/'))

for (const file of files) {
  // Rule 3: hooks contain no JSX. A .ts file cannot contain JSX syntax, so ban .tsx
  // and hand-written element factories.
  if (file.startsWith('src/hooks/')) {
    if (file.endsWith('.tsx'))
      failures.push(`${file}: hooks/ must not contain .tsx files (rule 3: no JSX in hooks)`)
    if (/\bcreateElement\s*\(|jsx-runtime/.test(readFileSync(file, 'utf8'))) {
      failures.push(`${file}: hooks/ must not create React elements (rule 3: no JSX in hooks)`)
    }
  }
  // Rule 4: route files are plain wiring. .ts only, so no JSX can sneak in.
  if (file.startsWith('src/routes/') && !file.endsWith('.ts')) {
    failures.push(`${file}: route files must be .ts (rule 4: no JSX in routes, put UI in a view)`)
  }
  // Folder layout: only the agreed top-level folders exist in src/.
  const top = file.split('/')[1]
  const allowedTop = [
    'routes',
    'views',
    'components',
    'hooks',
    'stores',
    'api',
    'loaders',
    'lib',
    'styles',
    'paraglide', // generated by Paraglide (gitignored); the only code not written by hand
  ]
  const allowedRootFiles = ['main.tsx', 'router.tsx', 'routeTree.gen.ts', 'vite-env.d.ts']
  if (file.split('/').length === 2 ? !allowedRootFiles.includes(top) : !allowedTop.includes(top)) {
    failures.push(`${file}: unexpected location; see "Folders" in AGENTS.md`)
  }
}

// Rule 6: every UI string lives in messages/*.json, in both languages with the same placeholders.
const messageKeys = (locale) => {
  const raw = JSON.parse(readFileSync(`messages/${locale}.json`, 'utf8'))
  return new Map(Object.entries(raw).filter(([key]) => key !== '$schema'))
}
const placeholders = (value) =>
  [...new Set(JSON.stringify(value).match(/\{[a-zA-Z_]+\}/g) ?? [])].sort().join(',')
const pl = messageKeys('pl')
const en = messageKeys('en')
for (const key of new Set([...pl.keys(), ...en.keys()])) {
  if (!pl.has(key)) failures.push(`messages/pl.json: missing key "${key}" (present in en.json)`)
  else if (!en.has(key))
    failures.push(`messages/en.json: missing key "${key}" (present in pl.json)`)
  else if (placeholders(pl.get(key)) !== placeholders(en.get(key)))
    failures.push(`messages: "${key}" uses different {placeholders} in pl.json and en.json`)
}

// Rule 7: no hard-coded UI text in views and components (components/ui is vendored shadcn).
// Flags JSX text with letters and string literals in text-bearing attributes; use m.*() instead.
const TEXT_ATTRIBUTES =
  /\b(?:placeholder|aria-label|aria-description|title|alt|label)="[^"{}]*\p{L}[^"{}]*"/u
// A line of loose words: JSX text that wraps onto its own line (no tags, braces, quotes or code).
const LOOSE_TEXT =
  /^[^<>{}=;()'"`/\\&|?:[\]]*\p{L}{2,}\s+[^<>{}=;()'"`/\\&|?:[\]]*\p{L}{2,}[^<>{}=;()'"`]*$/u
const JSX_TEXT = />\s*([^<>{}=;\n]*\p{L}[^<>{}=;\n]*)\s*</u
for (const file of handWritten) {
  if (!/^src\/(views|components)\/.*\.tsx$/.test(file) || file.startsWith('src/components/ui/'))
    continue
  readFileSync(file, 'utf8')
    .split('\n')
    .forEach((line, index) => {
      const code = line.trim()
      if (
        /^(\/\/|\*|import |export |return |type |interface |const |let |function |else |case |default )/.test(
          code,
        )
      )
        return
      if (TEXT_ATTRIBUTES.test(code) || JSX_TEXT.test(code) || LOOSE_TEXT.test(code))
        failures.push(
          `${file}:${index + 1}: hard-coded UI text, add it to messages/*.json (rule 7)`,
        )
    })
}

if (failures.length > 0) {
  console.error(
    `check-arch: ${failures.length} violation(s)\n${failures.map((f) => `  ✗ ${f}`).join('\n')}`,
  )
  process.exit(1)
}
console.log(`check-arch: ${handWritten.length} files OK, ${pl.size} messages in pl and en`)
