/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InterviewSpikeRouteImport } from './routes/interview-spike'
import { Route as InterviewSpikeCopilotkitRouteImport } from './routes/interview-spike-copilotkit'
import { Route as TripsRouteImport } from './routes/trips'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewSpikeRoute = InterviewSpikeRouteImport.update({
  id: '/interview-spike',
  path: '/interview-spike',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewSpikeCopilotkitRoute =
  InterviewSpikeCopilotkitRouteImport.update({
    id: '/interview-spike-copilotkit',
    path: '/interview-spike-copilotkit',
    getParentRoute: () => rootRouteImport,
  } as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/interview-spike': typeof InterviewSpikeRoute
  '/interview-spike-copilotkit': typeof InterviewSpikeCopilotkitRoute
  '/trips': typeof TripsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/interview-spike': typeof InterviewSpikeRoute
  '/interview-spike-copilotkit': typeof InterviewSpikeCopilotkitRoute
  '/trips': typeof TripsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/interview-spike': typeof InterviewSpikeRoute
  '/interview-spike-copilotkit': typeof InterviewSpikeCopilotkitRoute
  '/trips': typeof TripsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/interview-spike' | '/interview-spike-copilotkit' | '/trips'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/interview-spike' | '/interview-spike-copilotkit' | '/trips'
  id:
    | '__root__'
    | '/'
    | '/interview-spike'
    | '/interview-spike-copilotkit'
    | '/trips'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InterviewSpikeRoute: typeof InterviewSpikeRoute
  InterviewSpikeCopilotkitRoute: typeof InterviewSpikeCopilotkitRoute
  TripsRoute: typeof TripsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-spike': {
      id: '/interview-spike'
      path: '/interview-spike'
      fullPath: '/interview-spike'
      preLoaderRoute: typeof InterviewSpikeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-spike-copilotkit': {
      id: '/interview-spike-copilotkit'
      path: '/interview-spike-copilotkit'
      fullPath: '/interview-spike-copilotkit'
      preLoaderRoute: typeof InterviewSpikeCopilotkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InterviewSpikeRoute: InterviewSpikeRoute,
  InterviewSpikeCopilotkitRoute: InterviewSpikeCopilotkitRoute,
  TripsRoute: TripsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
